---
title: "Analysis for CHTC simulatoin studies"
output: 
  html_document: 
    number_sections: yes
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: inline
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
  library(data.table)
  library(rstanarm)
  library(rstan)
  library(parallel)
  library(xtable)
  library(ggplot2)
  library(ggthemes)
  library(kableExtra)
  library(LaplacesDemon)
  library(abind)
  library(dplyr)
  library(stringr)
  library(tidyverse)
```

# Functions

```{r}
# functions
alz <- function(ni, nj, sd, sigma){
a <- list.files(pattern = paste0(ni, "_", nj, "_sd", sd, "_sigma", sigma, "_out.RData"), full.names = T)  %>% map(~ mget(load(.))) 


for (i in 1:100){
  
  b <- a[[i]][1] %>% as.data.frame() 
  names(b) <- sub(pattern = ".*_ws.", replacement = "", x = names(b))
  assign(paste0("ws_", i, "_", ni, "_", nj, "_sd", sd, "_sigma", sigma), b)
  
  c <- a[[i]][2] %>% as.data.frame() %>% t()
  assign(paste0("kld_", i, "_", ni, "_", nj, "_sd", sd, "_sigma", sigma), c)
  
  d <- a[[i]][3] %>% as.data.frame() 
  names(d) <- sub(pattern = ".*.time_", replacement = "", x = names(d))
  assign(paste0("time_", i, "_", ni, "_", nj, "_sd", sd, "_sigma", sigma), d)

}

#  mean
ws <- mget(intersect(ls(pattern = paste0("ws_")), ls(pattern = paste0(ni, "_", nj, "_sd", sd, "_sigma", sigma))))%>%
      abind(along = 3)

o <- ws %>% apply(., 1:2, mean) %>% round(3)
p <- data.frame(Model = c("M1", "M5", "M11", "M15", "M12", 
                       "M6", "M13", "M7", "M2", "M8", 
                       "M14", "M9", "M3", "M10", "M4"), 
                      N = rep(ni*nj, 15),
                      sd = rep(sd, 15), o)

ws_mean <- p[c(1, 9, 13, 15, 2,
                     6, 8, 10, 12, 14,
                     3, 5, 7, 11, 4), ] %>% 
  pivot_longer(cols = bs:bhs, names_to = "Methods", values_to = "Weights") %>% 
  mutate(icc = ifelse(sd == 1.667, 0.1, 
                      ifelse(sd == 2.041, 0.2, 0.3)))

ws_mean[ws_mean == "pbmabb"] <- "PBMAPLUS"
ws_mean[ws_mean == "bs"] <- "BS"
ws_mean[ws_mean == "bhs"] <- "BHS"
ws_mean[ws_mean == "pbma"] <- "PBMA"
ws_mean$Methods <- factor(ws_mean$Methods, levels = c("BS", "BHS", "PBMA", "PBMAPLUS"))


ws_sd <- ws %>% apply(., 1:2, sd) %>% round(3)

assign(paste0("ws_all_mean", ni, "_", nj, "_sd", "_sigma", sigma), ws_mean)
assign(paste0("ws_all_sd", ni, "_", nj, "_sd", "_sigma", sigma), ws_sd)

klds <- mget(intersect(ls(pattern = paste0("kld_")), ls(pattern = paste0(ni, "_", nj, "_sd", sd, "_sigma", sigma))))%>%
      abind(along = 3)

kld_dist <- klds %>% apply(., 2:3, mean) %>% as.data.frame() %>% 
  mutate(methods = rownames(.)) %>% 
  pivot_longer(cols = !methods, names_to = "index", values_to = "kld_mean") %>% 
  mutate(N = rep(ni*nj, nrow(.)), sd = rep(sd, nrow(.))) %>% 
  select(!index)%>% 
  mutate(icc = ifelse(sd == 1.667, 0.1, 
                      ifelse(sd == 2.041, 0.2, 0.3))) 

kld_dist[kld_dist == "pbmabb"] <- "PBMAPLUS"
kld_dist[kld_dist == "bs"] <- "BS"
kld_dist[kld_dist == "bhs"] <- "BHS"
kld_dist[kld_dist == "pbma"] <- "PBMA"
kld_dist$methods <- factor(kld_dist$methods, levels = c("BS", "BHS", "PBMA", "PBMAPLUS"))
kld_dist$Methods <- kld_dist$methods

kld_mean <- klds %>% apply(., 1:2, mean)

kld_mean <- data.frame(sd = sd, N = ni*nj, kld_mean) %>% 
  mutate(icc = ifelse(sd == 1.667, 0.1, 
                      ifelse(sd == 2.041, 0.2, 0.3)))

kld_sd <- klds %>% apply(., 2, sd)
kld_sd <- data.frame(sd = sd, N = ni*nj, methods = names(kld_sd), kld_sd = kld_sd) %>% 
  mutate(icc = ifelse(sd == 1.667, 0.1, 
                      ifelse(sd == 2.041, 0.2, 0.3)))

assign(paste0("kld_dist", ni, "_", nj, "_sd", sd, "_sigma", sigma), kld_dist)
assign(paste0("kld_all_mean", ni, "_", nj, "_sd", sd, "_sigma", sigma), kld_mean)
assign(paste0("kld_all_sd", ni, "_", nj, "_sd", sd, "_sigma", sigma), kld_sd)

times <- mget(intersect(ls(pattern = paste0("time_")), ls(pattern = paste0(ni, "_", nj, "_sd", sd, "_sigma", sigma))))%>%
      abind(along = 3)
time_all_mean <- times %>% apply(., 1:2, mean) %>% as.data.frame()
time_mean <- data.frame(sd = sd, N = ni*nj, time_all_mean[,1])%>% 
  mutate(icc = ifelse(sd == 1.667, 0.1, 
                      ifelse(sd == 2.041, 0.2, 0.3))) %>% 
  mutate(Methods = c("bs", "pbma", "pbmabb", "bhs"))

# rownames(time_mean) <- c("bs", "pbma", "pbmabb", "bhs")
colnames(time_mean) <- c("sd", "N", "time_mean", "icc", "methods")
time_sd <- times %>% apply(., 1:2, sd)

assign(paste0("time_all_mean", ni, "_", nj, "_sd", sd, "_sigma", sigma), time_mean[1, ])
# assign(paste0("time_all_sd", ni, "_", nj, "_sd", sd, "_sigma", sigma), time_sd)

out <- list("ws_mean" = ws_mean, "ws_sd" = ws_sd, "kld_dist" = kld_dist,
            "kld_mean" = kld_mean, "kld_sd" = kld_sd, "time_mean" = time_mean)
return(out)

}

ni = 50;nj = 10;sd = 2.041;sigma = 0

```

# run
## sigma = 0
```{r}
# sigma = 0
a <- alz(ni = 50, nj = 10, sd = 1.667, sigma = 0)
b <- alz(ni = 150, nj = 30, sd = 1.667, sigma = 0)

c <- alz(ni = 50, nj = 10, sd = 2.041, sigma = 0)
d <- alz(ni = 150, nj = 30, sd = 2.041, sigma = 0)

e <- alz(ni = 50, nj = 10, sd = 5, sigma = 0)
f <- alz(ni = 150, nj = 30, sd = 5, sigma = 0)

```

## sigma = 5
```{r}
# sigma = 5
g <- alz(ni = 50, nj = 10, sd = 1.667, sigma = 5)
h <- alz(ni = 150, nj = 30, sd = 1.667, sigma = 5)

i <- alz(ni = 50, nj = 10, sd = 2.041, sigma = 5)
j <- alz(ni = 150, nj = 30, sd = 2.041, sigma = 5)

k <- alz(ni = 50, nj = 10, sd = 5, sigma = 5)
l <- alz(ni = 150, nj = 30, sd = 5, sigma = 5)

```

## sigma = 10
```{r}
# sigma = 5
m <- alz(ni = 50, nj = 10, sd = 1.667, sigma = 10)
n <- alz(ni = 150, nj = 30, sd = 1.667, sigma = 10)

o <- alz(ni = 50, nj = 10, sd = 2.041, sigma = 10)
p <- alz(ni = 150, nj = 30, sd = 2.041, sigma = 10)

q <- alz(ni = 50, nj = 10, sd = 5, sigma = 10)
r <- alz(ni = 150, nj = 30, sd = 5, sigma = 10)
```


# weights
## aggregation
```{r}

ws_sigma0 <- rbind(a$ws_mean, b$ws_mean, c$ws_mean, 
                   d$ws_mean, e$ws_mean, f$ws_mean) %>% 
  mutate(methods = recode(Methods, 'pbmabb' = 'pbmaplus'))
  

ws_sigma5 <- rbind(g$ws_mean, h$ws_mean, i$ws_mean, 
                   j$ws_mean, k$ws_mean, l$ws_mean)%>% 
  mutate(methods = recode(Methods, 'pbmabb' = 'pbmaplus'))

ws_sigma10 <- rbind(m$ws_mean, n$ws_mean, o$ws_mean, 
                   p$ws_mean, q$ws_mean, r$ws_mean)%>% 
  mutate(methods = recode(Methods, 'pbmabb' = 'pbmaplus'))

ws_sigma0 %>% kable() %>% kable_styling()
ws_sigma5 %>% kable() %>% kable_styling()
ws_sigma10 %>% kable() %>% kable_styling()

```

## bar charts
```{r}

mod_labels <- c("M1","M2","M3","M4","M5","M6","M7","M8","M9","M10","M11","M12","M13","M14","M15")

p1 <- ws_sigma0 %>% ggplot() +
  geom_bar(aes(x = factor(Model, levels = mod_labels), 
               y = Weights, fill = Methods),
           position = "stack", stat = "identity") +
  facet_grid(N~icc, labeller = label_both) + 
 theme_bw()+labs(x = "Models")

p2 <- ws_sigma5 %>% ggplot() +
  geom_bar(aes(x = factor(Model, levels = mod_labels), y = Weights, fill = Methods),
           position = "stack", stat = "identity")+
  facet_grid(N~icc, labeller = label_both)+
  theme_bw()+labs(x = "Models")

p3 <- ws_sigma10 %>% ggplot() +
  geom_bar(aes(x = factor(Model, levels = mod_labels), y = Weights, fill = Methods),
           position = "stack", stat = "identity")+
  facet_grid(N~icc, labeller = label_both)+
  theme_bw()+labs(x = "Models")

p1
p2
p3

wid <- 3456
hei <- 1989

#ggsave("ws_sigma0.png", plot = p1, width = wid, height = hei, limitsize = FALSE)
#ggsave("ws_sigma5.png", plot = p2, width = wid, height = hei, limitsize = FALSE)

```
## in case they want black and white plots
```{r}
ws_sigma0 %>% ggplot() +
  geom_bar(aes(x = Model, y = Weights, fill = Methods),
           position = "stack", stat = "identity")+
  scale_fill_brewer(type = "seq", palette = "Greys")+
  facet_grid(N~icc, labeller = label_both)+
  theme_bw()+labs(x = "models")

ws_sigma5 %>% ggplot() +
  geom_bar(aes(x = Model, y = Weights, fill = Methods),
           position = "stack", stat = "identity")+
  scale_fill_brewer(type = "seq", palette = "Greys")+
    facet_grid(N~icc, labeller = label_both)+
  theme_bw()+labs(x = "models")


ws_sigma10 %>% ggplot() +
  geom_bar(aes(x = Model, y = Weights, fill = Methods),
           position = "stack", stat = "identity")+
  scale_fill_brewer(type = "seq", palette = "Greys")+
  facet_grid(N~icc, labeller = label_both)+
  theme_bw()+labs(x = "models")


```

# kld
## mean of klds, round to digits = 6, sd of klds
```{r}
# mean of klds
mean_kld0 <- rbind(a$kld_mean, b$kld_mean, c$kld_mean, 
                   d$kld_mean, e$kld_mean, f$kld_mean) %>% 
  pivot_longer(cols = bs:bhs, names_to = "methods", values_to = "kld_mean")%>% 
  mutate(kld_mean = round(kld_mean, 10)) 

mean_kld5 <- rbind(g$kld_mean, h$kld_mean, i$kld_mean, 
                   j$kld_mean, k$kld_mean, l$kld_mean)%>% 
  pivot_longer(cols = bs:bhs, names_to = "methods", values_to = "kld_mean") %>% 
  mutate(kld_mean = round(kld_mean, 10)) 

mean_kld10 <- rbind(m$kld_mean, n$kld_mean, o$kld_mean, 
                   p$kld_mean, q$kld_mean, r$kld_mean)%>% 
  pivot_longer(cols = bs:bhs, names_to = "methods", values_to = "kld_mean") %>% 
  mutate(kld_mean = round(kld_mean, 10)) 

# sd of klds
sd_kld0 <- rbind(a$kld_sd, b$kld_sd, c$kld_sd, 
                   d$kld_sd, e$kld_sd, f$kld_sd) 

sd_kld5 <- rbind(g$kld_sd, h$kld_sd, i$kld_sd, 
                   j$kld_sd, k$kld_sd, l$kld_sd)

sd_kld10 <- rbind(m$kld_sd, n$kld_sd, o$kld_sd, 
                   p$kld_sd, q$kld_sd, r$kld_sd)

# dist of klds
dist_kld0 <- rbind(a$kld_dist, b$kld_dist, c$kld_dist, 
                   d$kld_dist, e$kld_dist, f$kld_dist)

dist_kld5 <- rbind(g$kld_dist, h$kld_dist, i$kld_dist, 
                   j$kld_dist, k$kld_dist, l$kld_dist)

dist_kld10 <- rbind(m$kld_dist, n$kld_dist, o$kld_dist, 
                   p$kld_dist, q$kld_dist, r$kld_dist)

```

## mean of klds
```{r}
mean_kld0 %>% kable(., caption = "sigma0") %>% kable_styling()
mean_kld5 %>% kable(., caption = "sigma5") %>% kable_styling()
mean_kld10 %>% kable(., caption = "sigma10") %>% kable_styling()
```

## SD of klds
```{r}
sd_kld0 %>% kable(., caption = "sigma0") %>% kable_styling()
sd_kld5 %>% kable(., caption = "sigma5") %>% kable_styling()
sd_kld10 %>% kable(., caption = "sigma10") %>% kable_styling()

```

# boxplot 
```{r}
d0 <- dist_kld0 %>% ggplot() +
  geom_boxplot(aes(x = methods, y = kld_mean, fill = Methods))+
  facet_grid(N ~ icc, labeller = label_both)+
  theme_bw() + labs(y = "KLD", x = "Methods")

d5 <- dist_kld5 %>% ggplot() +
  geom_boxplot(aes(x = methods, y = kld_mean, fill = Methods))+
  facet_grid(N ~ icc, labeller = label_both)+
  theme_bw() + labs(y = "KLD", x = "Methods")

d10 <- dist_kld10 %>% ggplot() +
  geom_boxplot(aes(x = methods, y = kld_mean, fill = Methods))+
  facet_grid(N ~ icc, labeller = label_both)+
  theme_bw() + labs(y = "KLD", x = "Methods")

d0
d5
d10

wid <- 9.29
hei <- 4.30

ggsave("dk0.png", plot = d0, width = wid, height = hei, limitsize = FALSE)
ggsave("dk5.png", plot = d5, width = wid, height = hei, limitsize = FALSE)
ggsave("dk10.png", plot = d10, width = wid, height = hei, limitsize = FALSE)

# ggsave("ws_sigma5.png", plot = p2, width = wid, height = hei, limitsize = FALSE)
  
```

# time
```{r}
time0 <- rbind(a$time_mean, b$time_mean, c$time_mean, 
                   d$time_mean, e$time_mean, f$time_mean) 

time5 <- rbind(g$time_mean, h$time_mean, i$time_mean, 
                    j$time_mean, k$time_mean, l$time_mean)
# %>% pivot_longer(bs.:bhs., names_to = "methods", values_to = "time")

time10 <- rbind(m$time_mean, n$time_mean, o$time_mean, 
               p$time_mean, q$time_mean, r$time_mean)
# %>% pivot_longer(bs.:bhs., names_to = "methods", values_to = "time")

time0 %>% kable(., caption = "sigma0") %>% kable_styling()
time5 %>% kable(., caption = "sigma0") %>% kable_styling()
time10 %>% kable(., caption = "sigma0") %>% kable_styling()

```

# Plot time

```{r}
t0 <- ggplot(time0, aes(x=methods, y=time_mean)) +
  geom_segment(aes(x=methods, xend=methods, y=0, yend=time_mean), color="skyblue") +
  facet_grid(N ~ icc, labeller = label_both)+
  geom_point( color="blue", size=2, alpha=0.8) +
  theme_light() +
  coord_flip() +
theme_bw() + labs(y = "Avg.Time", x = "Methods")

t5 <- ggplot(time5, aes(x=methods, y=time_mean)) +
  geom_segment(aes(x=methods, xend=methods, y=0, yend=time_mean), color="skyblue") +
  facet_grid(N ~ icc, labeller = label_both)+
  geom_point( color="blue", size=2, alpha=0.8) +
  theme_light() +
  coord_flip() +
theme_bw() + labs(y = "Avg.Time", x = "Methods")
 
 t10 <- ggplot(time10, aes(x=methods, y=time_mean)) +
  geom_segment(aes(x=methods, xend=methods, y=0, yend=time_mean), color="skyblue") +
  facet_grid(N ~ icc, labeller = label_both)+
  geom_point( color="blue", size=2, alpha=0.8) +
  theme_light() +
  coord_flip() +
theme_bw() + labs(y = "Avg.Time", x = "Methods") 

t0
t5
t10

ggsave("t0.png", plot = t0,limitsize = FALSE)
ggsave("t5.png", plot = t5, limitsize = FALSE)
ggsave("t10.png", plot = t10, limitsize = FALSE)
 
 
```


